### ISSUE TITLE
Unable to Run on Domain using Valet & Unable to Migrate

### ISSUE THREAD

**Issue by abbasmashaddy72** [savannabits/filament-tenancy-starter#5]
I am unable to run using Domain below is the `.env` given also I am unable to migrate the table to MySQL:

I am Not Using Docker

When I was Running `php artisan serve` I was able to open the login page as there is no database I was unable to login

`php artisan migrate` && `php artisan tenants:migrate` Does not work, Tried Upgrading the composer packages but still same

and also can you provide my some instruction how to use it means Can use it based on subdomain based or URL based

```
APP_NAME="VANADI ERP"
APP_ENV=local
APP_KEY=base64:o4gZe2QRkhs2/+xgd+8jmU2N+6qMkGfNdHD+UsqYSWE=
APP_DEBUG=true
APP_SCHEME='http'
APP_BASE_DOMAIN=filament-saas
APP_BASE_PORT=80
APP_BASE_HOST=${APP_BASE_DOMAIN}:${APP_BASE_PORT}

APP_URL=${APP_SCHEME}://${APP_BASE_HOST}
ASSET_URL=${APP_URL}
APP_COPYRIGHT="Savannabits Ltd"

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=filament-saas
DB_USERNAME=root
DB_PASSWORD=Pass@123
```

**Comment by jeremiahsherrill** [comment]
APP_NAME="VANADI ERP"
APP_ENV=local
APP_KEY=base64:o4gZe2QRkhs2/+xgd+8jmU2N+6qMkGfNdHD+UsqYSWE=
APP_DEBUG=true
APP_SCHEME='http'
APP_BASE_DOMAIN=filament-saas.test
APP_BASE_PORT=80
APP_BASE_HOST=filament-saas.test

APP_URL=${APP_SCHEME}://${APP_BASE_HOST}
ASSET_URL=${APP_URL}
APP_COPYRIGHT="Savannabits Ltd"

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=filament-saas
DB_USERNAME=root
DB_PASSWORD=Pass@123

wrong db port for mysql that was the posgres port number
You also don't need the port number if you are using valet

**Comment by jeremiahsherrill** [comment]
I got in up and running and was able to create a tenant and the subdomain is registered, but tenant('id') doesn't return anything.   That's the last hurdle I have with this

**Comment by jeremiahsherrill** [comment]
Also change this

Route::middleware([
    'web',
    'universal',
    TenancyServiceProvider::TENANCY_IDENTIFICATION,
    
    to 
    
    Route::middleware([
    'web',
    'universal',
    InitializeTenancyByDomainOrSubdomain::class,

**Comment by abbasmashaddy72** [comment]
Okay Brother I will Check Thanks

**Comment by abbasmashaddy72** [comment]
I was able to migrate but some UI issue & livewire issue:

I tried insailling livewire and setting up custom theme but no Change

![image](https://github.com/savannabits/filament-tenancy-starter/assets/55267488/0662ca94-7e6f-4aa2-9c56-d9c4d2b4ffd0)

**Comment by abbasmashaddy72** [comment]
I was successfully able to create the Tenant and was able to redirect to the subdomain as required but when I was Login from the tenant page it showed that `These credentials do not match our records.` but where I already created a user in User table in the tenant specific DB with the same credentials I was going to Login

**Comment by jeremiahsherrill** [comment]
Did you check the tenant db to make sure that user was created there?

**Comment by jeremiahsherrill** [comment]
oh btw there are things that are not setup yet, I don't actually think there is an admin system for the tenant by default.    I haven't really gone too deep into this just started myself

**Comment by abbasmashaddy72** [comment]
> Did you check the tenant db to make sure that user was created there?

I Created it manually

**Comment by abbasmashaddy72** [comment]
> oh btw there are things that are not setup yet, I don't actually think there is an admin system for the tenant by default. I haven't really gone too deep into this just started myself

Okay Brother, I will Check it out

If there is anything you had achieved, Please give the input that would be great
